name: Github Page

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  CI: true

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup shell
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          corepack enable
          yarn

      - name: Build
        id: build
        run: yarn workspace @react-beauty/demo build

      - name: Deploy to GitHub Pages
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          path: demo/dist
